# Generated by Django 5.0.3 on 2025-01-22 01:10

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('locations', '0001_initial'),
        ('profiles', '0002_employee'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.CreateModel(
            name='TalentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('headline', models.CharField(max_length=100)),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('locations', models.ManyToManyField(blank=True, related_name='talent_profiles', to='locations.location')),
                ('resume', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='documents.resume')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
