# Generated by Django 5.0.3 on 2025-04-07 02:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcripts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcript",
            name="session_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
