# Generated by Django 5.0.3 on 2025-04-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcripts", "0002_alter_transcript_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcript",
            name="category",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
