# Generated by Django 5.0.3 on 2025-04-09 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0001_initial"),
        ("transcripts", "0003_transcript_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcript",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="transcript",
            name="interview",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transcripts",
                to="interviews.interview",
            ),
        ),
    ]
