# Generated by Django 5.0.3 on 2025-04-17 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0001_initial"),
        ("transcripts", "0004_alter_transcript_category_alter_transcript_interview"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("location", "Location"),
                            ("availability", "Availability"),
                            ("schedule", "Schedule"),
                            ("academic_background", "Academic Background"),
                            ("interest", "Interest"),
                            ("prev_experience", "Prev Experience"),
                            ("teamwork", "Teamwork"),
                            ("communication", "Communication"),
                            ("preference", "Preference"),
                        ],
                        max_length=50,
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="interviews.interview",
                    ),
                ),
            ],
        ),
    ]
