# Generated by Django 5.2 on 2025-04-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcripts", "0005_interviewscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewscore",
            name="sentiment",
            field=models.CharField(
                blank=True,
                help_text="Sentiment of the answer: positive, neutral, negative",
                max_length=20,
                null=True,
            ),
        ),
    ]
