# Generated by Django 5.0.3 on 2025-06-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcripts", "0006_interviewscore_sentiment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewscore",
            name="sentiment",
        ),
        migrations.AlterField(
            model_name="interviewscore",
            name="category",
            field=models.CharField(
                choices=[
                    ("location", "Location"),
                    ("availability", "Availability"),
                    ("academic_background", "Academic Background"),
                    ("interest", "Interest"),
                    ("prev_experience", "Prev Experience"),
                ],
                max_length=50,
            ),
        ),
    ]
