# Generated by Django 5.0.3 on 2025-04-06 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        ("profiles", "0003_remove_profile_user_talentprofile_delete_employee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "start",
                    models.DateTimeField(
                        blank=True, help_text="Start time of the interview", null=True
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        blank=True, help_text="End time of the interview", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("awaiting_feedback", "Awaiting Feedback"),
                            ("complete", "Complete"),
                        ],
                        default="scheduled",
                        max_length=50,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to="profiles.talentprofile",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
