# Generated by Django 5.2 on 2025-04-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="final_score",
            field=models.FloatField(
                blank=True,
                help_text="Final weighted score for the interview",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="summary",
            field=models.TextField(
                blank=True, help_text="Final summary of the interview", null=True
            ),
        ),
    ]
