# Generated by Django 5.0.3 on 2025-05-20 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0002_interview_final_score_interview_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume_summary", models.TextField()),
                ("interview_summary", models.TextField()),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("recommended", "Recommended"),
                            ("not recommended", "Not Recommended"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "key_insights",
                    models.JSONField(
                        default=list,
                        help_text="List of 5 key insights, each with a 'text' and 'label' (good/bad)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interview",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="interviews.interview",
                    ),
                ),
            ],
        ),
    ]
