# Generated by Django 5.0.3 on 2025-06-24 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0003_interviewreport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interview",
            name="summary",
        ),
    ]
